### ISSUE TITLE
Task List:

### ISSUE THREAD

**Issue by SiimonStark** [SiimonStark/JP_VanillaJS-Challenge#7]
- [x] Get Data from Form
- [x] Save Data to LocalStorage
- [x] Pull Data from LocalStorage
- [x] Display info on DOM
- [x] Delete Card
- [x] Delete from LocalStorage

**_Did not finish: Spent about 6hrs on this project, including styling_**

- [ ] Update Quality of Card
- [ ] Add custom Quality types
- [ ] Favorite Card
